### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by ghost** [sipwise/libtcap#1]
What's the license for this code? Is it the same as mediaproxy-ng/rtpengine?

**Comment by guillemj** [comment]
Hi!

The code was intended to be GPL+3, it's now been clarified in the debian/copyright file.

Thanks,
Guillem

**Comment by ghost** [comment]
Thanks for clarification! Might be a good idea to add LICENSE file similar to the way it's done in rtpengine repo - not everyone is smart enough to look into debian/copyright :)
