### ISSUE TITLE
Get all tcap components at once

### ISSUE THREAD

**Issue by thiennguu** [sipwise/libtcap#3]
Hi,

I'm using your library to decode the tcap message, in the case of multiple components in a tcap message, I do not know how to get all the components at once. Please show me.

Thank you

**Comment by rfuchs** [comment]
There's no support for extracting multiple values in one go. You can iterate through the message components by first extracting e.g. "end.components.0..." then extracting "end.components.1..." and so on.

**Comment by guillemj** [comment]
As this seems that can be accomplished by iterating, I'm thus closing the issue.
