### ISSUE TITLE
libtcap-mr12.4.1.1 make error

### ISSUE THREAD

**Issue by chantwao** [sipwise/libtcap#4]
make[1]: Leaving directory `/home/chentao/test/libtcap-mr12.4.1.1/asn1'
make -C src
make[1]: Entering directory `/home/chentao/test/libtcap-mr12.4.1.1/src'
gcc -g -Wall -O3 -fPIC -D_DEFAULT_SOURCE -I../asn1 -I../include  -c -o tcap.o tcap.c
tcap.c: In function ‘tcap_encode_with_routing’:
tcap.c:114:13: error: ‘asn_TYPE_descriptor_t’ has no member named ‘free_struct’
  asn_DEF_ANY.free_struct(&asn_DEF_ANY, cmp.choice.invoke.parameter, 0);
             ^
tcap.c: In function ‘tcap_decode’:
tcap.c:128:19: error: ‘asn_TYPE_descriptor_t’ has no member named ‘free_struct’
  asn_DEF_TCMessage.free_struct(&asn_DEF_TCMessage, ret, 0);
                   ^
tcap.c: In function ‘inap_decode’:
tcap.c:158:10: error: ‘asn_TYPE_descriptor_t’ has no member named ‘free_struct’
   (*type)->free_struct(*type, arg, 0);
          ^
tcap.c: In function ‘asn1_extract’:
tcap.c:255:11: error: ‘asn_TYPE_descriptor_t’ has no member named ‘print_struct’
   if (type->print_struct == CHOICE_print) {
           ^
tcap.c:256:16: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
    choice_spec = type->specifics;
                ^
tcap.c:276:10: error: ‘asn_TYPE_descriptor_t’ has no member named ‘print_struct’
  if (type->print_struct && out)
          ^
tcap.c:277:7: error: ‘asn_TYPE_descriptor_t’ has no member named ‘print_struct’
   type->print_struct(type, element, 0, cb, out);
       ^
tcap.c: In function ‘tcap_extract’:
tcap.c:297:19: error: ‘asn_TYPE_descriptor_t’ has no member named ‘free_struct’
  asn_DEF_TCMessage.free_struct(&asn_DEF_TCMessage, tcm, 0);
                   ^
tcap.c: In function ‘inap_extract’:
tcap.c:370:19: error: ‘asn_TYPE_descriptor_t’ has no member named ‘free_struct’
  asn_DEF_TCMessage.free_struct(&asn_DEF_TCMessage, tcm, 0);
                   ^
tcap.c:371:6: error: ‘asn_TYPE_descriptor_t’ has no member named ‘free_struct’
  type->free_struct(type, parameter, 0);
      ^
tcap.c:377:20: error: ‘asn_TYPE_descriptor_t’ has no member named ‘free_struct’
   asn_DEF_TCMessage.free_struct(&asn_DEF_TCMessage, tcm, 0);
                    ^
make[1]: *** [tcap.o] Error 1
make[1]: Leaving directory `/home/chentao/test/libtcap-mr12.4.1.1/src'
make: *** [all] Error 2
[root@localhost libtcap-mr12.4.1.1]# asn1c -version
ASN.1 Compiler, v0.9.29
Copyright (c) 2003-2017 Lev Walkin <vlm@lionet.info> and contributors.
[root@localhost libtcap-mr12.4.1.1]#

**Comment by chantwao** [comment]
Is this issue related to the version of asn1c?

**Comment by mika** [comment]
@chantwao on what distribution are you building?

**Comment by chantwao** [comment]
> @chantwao on what distribution are you building?

ASN.1 Compiler, v0.9.29

**Comment by mika** [comment]
on what **distribution**, the asn1 version is visible already

**Comment by chantwao** [comment]
> on what **distribution**, the asn1 version is visible already

it works well on ASN.1 Compiler, v0.9.28, but not on v0.9.29.



[root@localhost tests]# ./basic 
inap_extract ConnectArg: returned 0, value: 0x33 0x31 0x20 0x33 0x32 0x20 0x33 0x33 0x20 0x33 0x34 0x20 0x33 0x35 0x20 0x33 0x36 0x20 0x33 0x37 0x20 0x33 0x38 0x20 0x33 0x39 0x20 0x33 0x30 
[root@localhost tests]# ./encode 
ret: 30
buffer: 0x62 0x1c 0x48 0x00 0x6c 0x18 0xa1 0x16 0x02 0x01 0x00 0x02 0x01 0x14 0x30 0x0e 0xa0 0x0c 0x04 0x0a 0x31 0x32 0x33 0x34 0x35 0x36 0x37 0x38 0x39 0x30 
[root@localhost tests]# asn1c -verion
ASN.1 Compiler, v0.9.28
Copyright (c) 2003-2016 Lev Walkin <vlm@lionet.info>
[root@localhost tests]#

**Comment by chantwao** [comment]
The asn1c version higher than v0.9.28 is not available.
